// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todo_list_backend.Data;

#nullable disable

namespace todo_list_backend.Migrations
{
    [DbContext(typeof(TodoListDbContext))]
    [Migration("20240622080842_RemovedAdditionalDetailsBool")]
    partial class RemovedAdditionalDetailsBool
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("todo_list_backend.Data.Models.SubTodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SubTodoIsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("SubTodoIsOverdue")
                        .HasColumnType("bit");

                    b.Property<Guid>("TodoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("SubTodoItems");
                });

            modelBuilder.Entity("todo_list_backend.Data.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TodoIsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("TodoIsOverdue")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("todo_list_backend.Data.Models.SubTodoItem", b =>
                {
                    b.HasOne("todo_list_backend.Data.Models.TodoItem", null)
                        .WithMany("SubTodoItems")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("todo_list_backend.Data.Models.TodoItem", b =>
                {
                    b.Navigation("SubTodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
